### ISSUE TITLE
Desktop notifications on `core24`

### ISSUE THREAD

**Issue by jnsgruk** [snapcore/snapcraft-desktop-integration#28]
Having updated a few desktop snaps to core24, it was observed that notifications no longer work correctly, in that the app name isn't displayed properly.

Bug reports are: 
- https://github.com/snapcrafters/discord/issues/221
- https://github.com/snapcrafters/mattermost-desktop/issues/107#issuecomment-2271241333

And I've also observed it on Signal, too.

In [this Discourse thread](https://forum.snapcraft.io/t/gnome-notifications-on-core24-with-gnome-extension/41324), it was pointed out:

> libnotify4 was changed to use XDG Desktop Portal for notifications in 0.8.0 (included in core24).Workaround until the new path is fixed: NOTIFY_IGNORE_PORTAL=1 in the environment

We should look to update this repo to add this env var automatically to apps until the issue is resolved, which will likely need work in `snapd`.

(cc. @jhenstridge @sergio-costas)

**Comment by jnsgruk** [comment]
Thanks folks! Any idea when this will be "released" and I can drop the manual workaround in my snaps?

**Comment by ottok** [comment]
This issue is referenced from https://documentation.ubuntu.com/snapcraft/stable/how-to/integrations/craft-an-electron-app/#example-discord-project-file - should it be updated now that issue is fixed?
